version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: "install mockery"
          command: go get github.com/vektra/mockery/v2/.../
      - run:
          name: "codegen"
          command: go generate ./...
      - run:
          name: "go vet"
          command: go vet ./...
      - run:
          name: "gofmt"
          command: if [ "$$(gofmt -l . | wc -l)" -ne 0 ]; then echo "FAIL. Some files are not formatted:"; gofmt -l .; exit 1; fi
      - run:
          name: "test"
          command: go test -timeout 10s ./...
       
