// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// MountHelperMock is an autogenerated mock type for the mountHelper type
type MountHelperMock struct {
	mock.Mock
}

// MustChdir provides a mock function with given fields: dir
func (_m *MountHelperMock) MustChdir(dir string) {
	_m.Called(dir)
}

// MustChroot provides a mock function with given fields: to
func (_m *MountHelperMock) MustChroot(to string) {
	_m.Called(to)
}

// MustMkdir provides a mock function with given fields: path, perm
func (_m *MountHelperMock) MustMkdir(path string, perm os.FileMode) {
	_m.Called(path, perm)
}

// MustMount provides a mock function with given fields: src, dst, typ, flags, data
func (_m *MountHelperMock) MustMount(src string, dst string, typ string, flags uintptr, data string) {
	_m.Called(src, dst, typ, flags, data)
}

// MustSymlink provides a mock function with given fields: file, newname
func (_m *MountHelperMock) MustSymlink(file string, newname string) {
	_m.Called(file, newname)
}
